version: '3'

services:
  frontend:
    image: pizza/frontend
    build:
      context: .
      dockerfile: Frontend.Dockerfile
  ingredients:
    image: pizza/ingredients
    build:
      context: .
      dockerfile: Ingredients.Dockerfile
  orders:
    image: pizza/orders
    build:
      context: .
      dockerfile: Orders.Dockerfile
